### ISSUE TITLE
Homebridge crashes 

### ISSUE THREAD

**Issue by mach1009** [aprosvetova/homebridge-http-doorbell#1]
with this error

> TypeError: Cannot read property 'ring' of undefined
    at HTTPDoorbell.httpHandler (/usr/local/lib/node_modules/homebridge-http-doorbell/index.js:50:39)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-http-doorbell/index.js:20:14)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

**Comment by felix-mcfly** [comment]
I have the same error.
<img width="682" alt="screenshot 2018-04-02 17 02 02" src="https://user-images.githubusercontent.com/37754598/38201180-98f4bd8e-3697-11e8-99d4-134a9a80c8b2.png">

**Comment by anna-oake** [comment]
What id's do you use in configuration?
What url do you request?
If you have id "frontDoor" and port "9053", you should use:
`http://{ip_address}:9053/frontDoor`
Please note that you can't put a slash in the end.

**Comment by pccaredk** [comment]
Hi. I get the exact same error...

**Comment by phenotypic** [comment]
Getting the same issue here, only started recently though which is strange. I've tried reinstalling both the plugin and Homebridge. I've also updated to the newest node etc. Any ideas?

**Comment by phenotypic** [comment]
For those still experiencing this error, I have forked `homebridge-http-motion-sensor` and simplified it to function in much the same way as `homebridge-http-doorbell` in an attempt to work around the issue. If you are interested, you can view it [here](https://github.com/Tommrodrigues/homebridge-http-motion-sensor). 

Kind regards, Tom

**Comment by alc7328** [comment]
When I access the url http://{my_ip_address}:{my_port}/{my_id} Homebridge instantly crashes. I'm looking at the log and says "Got SIGTERM, shutting down Bridge..."
